const citateNietzsche = [
	'Pentru a prezice comportamentul oamenilor obișnuiți trebuie doar să presupui că ei vor încerca de fiecare dată să scape dintr-o situație grea folosindu-se de cel mai mic cuantum de inteligența posibil.',
	'Ajută-te pe tine însuți și toată lumea te va ajuta.',
	'Dacă te uiți mult timp în abis, abisul se va uita la rândul său în tine.',
	'Trebuie să-ți dorești să fii puternic. Altfel, nu vei ajunge așa niciodată.',
	'Timpul este focul în care ne ardem toți existența.',
	'Nu sunt supărat pentru că m-ai mințit. Sunt supărat pentru că de acum nu te mai pot crede.',
	'Din paradis lipsesc toți oamenii interesanți.',
	'Dragostea este oarbă; prietenia doar închide ochii.',
	' Avantajul unei memorii proaste este faptul că îți permite să te bucuri de mai multe ori de lucrurile bune ca și cum ar fi pentru prima dată.',
	'Pentru ființa cea mai puternică, răul nu vine de la cel puternic, ci de la cel slab.',
	'Fiecare biserică este o piatră pe mormanul omului bun – nu vrea sub nicio formă ca el să se ridice din nou.',
	'Cunoscătorul trebuie să fie capabil nu doar să își iubească inamicii ci de asemenea, să își urască prietenii.',
	'Nimeni nu cunoaște, nici nu poate cunoaște, partea cea mai bună ascunsă în adâncul lui.',
	'Femeia e o suprafață care simulează adâncimea.',
	'Uneori, rămâi fidel unei cauze doar pentru că oponenții tăi nu încetează să fie insipizi.',
	'Mulți oameni așteaptă o viață întreagă pentru șansa de a fi buni în stilul lor propriu.',
	'Fă ce vrei, dar înainte pune-te în rândul celor care ştiu ce vreau.',
	'Libertatea înseamnă să fim responsabili pentru noi înșine.',
	' Vrednic de cinstire este tot ce pare anevoios.',
	'Iraționalitatea unui lucru nu este un argument împotriva existenței sale ci mai degrabă o condiție a acesteia.',
	'Viața înseamnă a transforma constant în lumină și în flacără tot ceea ce suntem și tot ce întâlnim.',
	'Ai căutat cea mai grea povară și atunci te-ai găsit pe tine însuți.',
	'E greu să trăieşti printre oameni fiindcă-i greu să taci.',
	'Ceea ce faci din iubire se întâmplă întotdeauna dincolo de bine și de rău.',
	'Credința înseamnă să nu vrei să știi ce este adevărat.',
	'Te duci la femei? Nu uita biciul!',
	'A-ți uita scopul este cea mai comuna forma de prostie.',
	'Se poate aprecia calitatea unui om după cantitatea de singurătate pe care o poate suporta.',
	'Omul este cel mai crud animal.',
	'Nu puterea marilor sentimente face oamenii superiori, ci durata lor.',
	'Fără muzică, viața ar fi o greșeală.',
	'Ceea ce nu ne omoară, ne face mai puternici.',
	'Moralitatea este instinctul de turmă al individului.',
	'Trebuie să ai memorie bună pentru a-ți putea ține toate promisiunile făcute.',
	'Omul este ceva ce trebuie depășit.',
	'Care este adevărul? E omul una din gafele lui Dumnezeu sau Dumnezeu e una din cele ale omului?',
	'Cel ce luptă cu monștri ar trebui să aiba grijă să nu devină unul.',
	'Ai nevoie de haos în suflet pentru a putea da naștere unei stele.',
	'Omul este o frânghie care leagă bestia de supraom – o frânghie peste abis.',
	'Îmi cunosc limitele. Dar pur şi simplu le ignor.',
	'Iubirea este o stare în care omul vede lucrurile exact așa cum nu sunt.',
	'Iubirii îi este mai frică de schimbare decât de distrugere.',
	'Nu există preț prea mare pentru privilegiul de a fi propriul tău stăpân.',
	' Câtă melancolie în orice lucru încheiat!',
	'Libertatea este absența gândirii individuale.',
	'Credința: refuzul de a ști ceea ce este adevărat.',
	'Vizionarul se minte pe sine, mincinosul pe ceilalți.',
	'Uneori, oamenii nu vor să audă adevărul deoarece nu vor să le fie distruse iluziile.',
	'Uitarea şi mersul mai departe sunt cea mai mare înțelepciune.'
]

export default citateNietzsche;